
package ma.esoftech.esoftrade.service.user;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import ma.esoftech.esoftrade.model.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "User.Service.esoftrade.esoftech.ma")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @return
     *     returns java.util.List<ma.esoftech.esoftrade.service.user.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserList", targetNamespace = "User.Service.esoftrade.esoftech.ma", className = "ma.esoftech.esoftrade.service.user.GetUserList")
    @ResponseWrapper(localName = "getUserListResponse", targetNamespace = "User.Service.esoftrade.esoftech.ma", className = "ma.esoftech.esoftrade.service.user.GetUserListResponse")
    @Action(input = "User.Service.esoftrade.esoftech.ma/UserService/getUserListRequest", output = "User.Service.esoftrade.esoftech.ma/UserService/getUserListResponse")
    public List<User> getUserList();

}
